<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Krypton.Toolkit.Suite.Extended.Outlook.Grid" Version="105.26.4.110" />
    <PackageReference Include="Krypton.Toolkit.Suite.Extended.TreeGridView" Version="105.26.4.110" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Codex.CommandEngine.Abstractions\Codex.CommandEngine.Abstractions.csproj" />
  </ItemGroup>
</Project>
